### ISSUE TITLE
'System.Dynamic.ExpandoObject' does not contain a definition for 'data'

### ISSUE THREAD

**Issue by Leproide** [Corsinvest/cv4pve-botgram#10]
Ciao!
Qualsiasi comando tento di utilizzare la risposta è sempre questa:
Error execute command! 'System.Dynamic.ExpandoObject' does not contain a definition for 'data'
Ad esempio ho provato /vmshutdown, poi /vmshutdown 100 oppure /vmshutdown *nomevm* ma l'errore è sempre quello.
Sbaglio qualcosa e c'è qualche documentazione disponibile o non funziona più con le nuove versioni di proxmox?

--------------------

HI!
Whatever command I try to use the response is always this:
Error execute command! 'System.Dynamic.ExpandoObject' does not contain a definition for 'data'
For example I tried /vmshutdown, then /vmshutdown 100 or /vmshutdown *vmname* but the error is always the same.
Am I doing something wrong and is there any documentation available or does it no longer work with new versions of proxmox?

**Comment by franklupo** [comment]
Run with --debig and attaché log.
The user have s permissione?

**Comment by Leproide** [comment]
Hi, tnx for the reply
If i run with --debug no file are generated

```
Message: /help
01/27/2024 22:19:17 - Chat Id: 'censored' User: 'censored' - 'censored' Msg Type: 'Text'=> '/vmstop'
Message: /vmstop
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Corsinvest.ProxmoxVE.Api.ResultExtension.ToData(Result result)
   at Corsinvest.ProxmoxVE.Api.ResultExtension.ToModel[T](Result result)
   at Corsinvest.ProxmoxVE.Api.Extension.ModelsExtensionsAutoGen.Get(PveResources item, String type)
   at Corsinvest.ProxmoxVE.Api.Extension.ModelsExtensions.Get(PveResources item, ClusterResourceType resourceType)
   at Corsinvest.ProxmoxVE.Api.Extension.ClientExtension.GetResources(PveClient client, ClusterResourceType resourceType)
   at Corsinvest.ProxmoxVE.TelegramBot.Helpers.Api.BotHelper.ChooseVmInlineKeyboard(TelegramBotClient botClient, Int64 chatId, PveClient pveClient, Boolean isRunning)
   at Corsinvest.ProxmoxVE.TelegramBot.Commands.Vm.Api.Base.Execute(Message message, TelegramBotClient botClient)
   at Corsinvest.ProxmoxVE.TelegramBot.Api.BotManager.ProcessMessage(Message message)
01/27/2024 22:20:14 - Chat Id: 'censored' User: 'censored' - 'censored' Msg Type: 'Text'=> '/vmstop'
Message: /vmstop
   at CallSite.Target(Closure , CallSite , Object )
   at Corsinvest.ProxmoxVE.Api.ResultExtension.ToData(Result result)
   at Corsinvest.ProxmoxVE.Api.ResultExtension.ToModel[T](Result result)
   at Corsinvest.ProxmoxVE.Api.Extension.ModelsExtensionsAutoGen.Get(PveResources item, String type)
   at Corsinvest.ProxmoxVE.Api.Extension.ModelsExtensions.Get(PveResources item, ClusterResourceType resourceType)
   at Corsinvest.ProxmoxVE.Api.Extension.ClientExtension.GetResources(PveClient client, ClusterResourceType resourceType)
   at Corsinvest.ProxmoxVE.TelegramBot.Helpers.Api.BotHelper.ChooseVmInlineKeyboard(TelegramBotClient botClient, Int64 chatId, PveClient pveClient, Boolean isRunning)
   at Corsinvest.ProxmoxVE.TelegramBot.Commands.Vm.Api.Base.Execute(Message message, TelegramBotClient botClient)
   at Corsinvest.ProxmoxVE.TelegramBot.Api.BotManager.ProcessMessage(Message message)
```

**Comment by franklupo** [comment]
The user proxmox have permission for list VM and shurdown?
Try tò use root

**Comment by Leproide** [comment]
I use the root account.
The password contain a !, is that the problem?

screen -S cv4pve-botgram -d -m ./cv4pve-botgram --host=192.168.1.30 --username=root@pam --password=censored!123 --token censored:censored --chatsId censored --debug

Ok i'm stupid... root@pam, my fault i read now... copy paste error
I try only with root

EDIT:
Same error:
Error execute command! 'System.Dynamic.ExpandoObject' does not contain a definition for 'data'

**Comment by Leproide** [comment]
Ok resolved, the problem are (i think) the ! in the password, i created a new user and the bot works
Tnx :)

**Comment by franklupo** [comment]
Try to quote a password

Best regards

**Comment by Leproide** [comment]
Tryed and not working
i created a new user for the bot with a new password without special characters and all works
Tnx :)

**Comment by franklupo** [comment]
Which version Proxmox VE do you use?

**Comment by Leproide** [comment]
8.1.4

**Comment by franklupo** [comment]
in the new release it is fixed

**Comment by Leproide** [comment]
Perfect, thank you :)
